### ISSUE TITLE
Cygwin support is broken

### ISSUE THREAD

**Issue by mtl1979** [jfriesne/muscle#7]
In various places MUSCLE code mixes headers from GNU libc and headers from WIN32 APi which results in duplicate conflicting prototypes for standard I/O and networking related functions.

Some recently added code assumes WIN32 API is always used on Windows and results in preprocessor errors.

Only workaround is to check for presence of `_WIN32` define and only then use WIN32 API. Cygwin API should always prefered when `__CYGWIN__` is defined even though not using Cygwin itself, as MinGW (also defines `__MINGW32__` and `__MiNGW64__`) and MSYS (also defines `__MSYS__`) both define it and use GNU headers forked from Cygwin.

Currently a lot of places have fragments `#if WIN32` or `#elif WIN32` which error out on Cygwin-based systems as `WIN32` is no more defined for Cygwin-based systems and results in zero-length conditional when using gcc as undefined preprocessor macros/defines don't expand to literal `0`.

**Comment by jfriesne** [comment]
This isn't something I'm in a position to work on, since I don't use Cygwin (my Windows development is under MSVC).  If you want to try to sort it out and submit a patch or pull-request, I will try to integrate the fix (assuming it doesn't break the environments that I do use, too much :) )

**Comment by jfriesne** [comment]
Btw WIN32 should be defined to 1 at line 120 of MuscleSupport.h; perhaps you want to add a || defined(__CYGWIN__) at line 118 of that file?

**Comment by mtl1979** [comment]
Obviously for current versions it should stay undefined as the same code that works for MSVC won't work on Cygwin et al.

I'm not expert in Cygwin low-level networking API, so I don't know how to implement the missing code. I created the issue to see if someone else who uses MUSCLE and has better knowledge of the API could help...
